### ISSUE TITLE
Stack compatibility (GHC_PACKAGE_PATH is incompatible with Cabal)

### ISSUE THREAD

**Issue by chris-martin** [hdevtools/hdevtools#6]
This issue is from https://github.com/bitc/hdevtools/issues/41 - I'm copying it here because that repo seems to have been abandoned.

Running hdevtools via `stack exec` as the readme instructs, this is the result:

```
> stack exec --no-ghc-package-path hdevtools -- check Foo.hs 
Cabal error: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times).
```

Any workaround, however ugly, would be great.

**Comment by ranjitjhala** [comment]
Hi Chris, the workaround is to just run directly (i.e. without `stack exec`). 

This has been working for me since at least 0.1.2.1.

Can you check if that works for you? Thanks!

**Comment by ch1bo** [comment]
Which version of `stack` are you using? `--no-ghc-package-path` should explicitly remove `GHC_PACKAGE_PATH` from the execution environment, but prior to stack 0.1.1.0 the flag might be not available.

**Comment by chris-martin** [comment]
I don't have any haskell stuff installed globally so that I can use different versions of ghc et al for different projects.

`--no-ghc-package-path` does remove the environment variable, but then it seems that cabal isn't getting the package path at all.

```
> stack exec --no-ghc-package-path -- hdevtools check src/Data/Money.hs 
Cabal error: At least the following dependencies are missing:
    Decimal -any,
    aeson -any,
    hspec -any,
    split -any,
    text -any,
    wreq -any
```

I also opened a similar issue on [Stack](https://github.com/commercialhaskell/stack/issues/1793)

**Comment by ch1bo** [comment]
Now that looks more like the dependencies are not installed (I know, captain obvious speaking :). Currently, hdevtools loads all targets and thus dependencies for tests and benchmarks have to be available in the package dbs. So be sure to call once `stack build --test --bench`. Does that work? Also make sure no cabal sandbox (config) resides in the project root as this would be prioritized.

**Comment by chris-martin** [comment]
`stack build --test --bench` does work, and `hdevtools` still does not.

I don't know what a cabal sandbox config is :)

**Comment by ch1bo** [comment]
Ok, what are your versions and paths, i.e. `stack --version`, `hdevtools --version`, `which ghc`, `stack ghc -- --version`, `stack path` etc.

I saw that you are using nix and unfortunately I don't have much experience with it. I suspect that hdevtools does not use the correct (i.e. nix's) package dbs.

**Comment by chris-martin** [comment]
```
> stack --version
Version 1.0.2 x86_64
```

```
> stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```

```
> stack exec -- hdevtools --version
hdevtools: version 0.1.2.2 (ghc-7.10.3-x86_64-linux, cabal-1.22.5.0)
```

```
> stack exec -- which ghc
/nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/bin/ghc
```

```
> stack path
global-stack-root: /home/chris/.stack
project-root: /home/chris/foo
config-location: /home/chris/foo/stack.yaml
bin-path: /home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3/bin:/nix/store/5mda3rvbriy9pahnw1wdnhhlfhzvi7mw-glpk-4.56/bin:/nix/store/gnh3530v31km5ymkl8c8h91wa5fnb6fk-pcre-8.37/bin:/nix/store/60wip6x0icg08vxv0z21fx1ngwsdlb2x-cabal-install-1.22.7.0/bin:/nix/store/d3ricygdak9n3c3x9wv8xvb1nja1dxhg-hdevtools-0.1.2.2/bin:/nix/store/ad82c6xh39blh32d99wv1kjxqfjxqkn2-sublimetext3-3083/bin:/nix/store/6l2i0yb4l2ykhjc39h6v59k6qlnck02m-which-2.21/bin:/nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/bin:/nix/store/l15rppxw3fjyysslj160q31jc7pkqb32-patchelf-0.8/bin:/nix/store/5kicd5g9w5fnn10zv6v3f3j63g2r4c72-paxctl-0.9/bin:/nix/store/bkllwvss62hch8vgxacnpdnvmlldwfxn-gcc-wrapper-4.9.3/bin:/nix/store/9s9r019176g7cvn2nvcw41gsp862y6b4-coreutils-8.24/bin:/nix/store/6hrcxzwk3padb28i3phnmmz15bjjqaj3-findutils-4.4.2/bin:/nix/store/5pa28il3q8v61zvfx1v3kwgw9g6alv1x-diffutils-3.3/bin:/nix/store/a8md7hpm9drjmdhgla0l3pf7llwdkm31-gnused-4.2.2/bin:/nix/store/dy92hq6ryvaj5bx5c6gi6fvnhyxdh78x-gnugrep-2.22/bin:/nix/store/sfccmsc4fwk11w7blz3g0q2hzi9va8f7-gawk-4.1.3/bin:/nix/store/q26acv90dg3iywdfk2q029ixdr3i19rh-gnutar-1.28/bin:/nix/store/xgz5hs1cvlx4vn98qizpqp8x5gwplqks-gzip-1.6/bin:/nix/store/icv8p8zxwdr6ljxb89vyxrmma7h2iqlh-bzip2-1.0.6/bin:/nix/store/n01xbf2w6x5bvxznmllpz60vx5ylpgjj-gnumake-4.1/bin:/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin:/nix/store/fgqamjbhxx6d62myqnp62i7b0bka2yiq-patch-2.7.5/bin:/nix/store/dkwhsgc5qa52hbpn3pg9zzz4kqsclzv0-xz-5.2.2/bin:/nix/store/5idnvskkm4hky2fj335xfbqpfim3g9pd-gcc-4.9.3/bin:/nix/store/iyw7cmmg2yi5cwc1pswfm0wrn1ssk1zh-binutils-2.23.1/bin:/nix/store/n2wxp513rr00f6hr2dy0waqahns49dch-glibc-2.21/bin:/nix/store/9s9r019176g7cvn2nvcw41gsp862y6b4-coreutils-8.24/bin
ghc-paths: /home/chris/.stack/programs/x86_64-linux-nix
local-bin-path: /home/chris/.local/bin
extra-include-dirs: /nix/store/5mda3rvbriy9pahnw1wdnhhlfhzvi7mw-glpk-4.56/include, /nix/store/60wip6x0icg08vxv0z21fx1ngwsdlb2x-cabal-install-1.22.7.0/include, /nix/store/6l2i0yb4l2ykhjc39h6v59k6qlnck02m-which-2.21/include, /nix/store/ad82c6xh39blh32d99wv1kjxqfjxqkn2-sublimetext3-3083/include, /nix/store/b305mbis40fmrnnizsfbccq9idk82aia-zlib-1.2.8/include, /nix/store/d3ricygdak9n3c3x9wv8xvb1nja1dxhg-hdevtools-0.1.2.2/include, /nix/store/gnh3530v31km5ymkl8c8h91wa5fnb6fk-pcre-8.37/include, /nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/include
extra-library-dirs: /nix/store/5mda3rvbriy9pahnw1wdnhhlfhzvi7mw-glpk-4.56/lib, /nix/store/60wip6x0icg08vxv0z21fx1ngwsdlb2x-cabal-install-1.22.7.0/lib, /nix/store/6l2i0yb4l2ykhjc39h6v59k6qlnck02m-which-2.21/lib, /nix/store/ad82c6xh39blh32d99wv1kjxqfjxqkn2-sublimetext3-3083/lib, /nix/store/b305mbis40fmrnnizsfbccq9idk82aia-zlib-1.2.8/lib, /nix/store/d3ricygdak9n3c3x9wv8xvb1nja1dxhg-hdevtools-0.1.2.2/lib, /nix/store/gnh3530v31km5ymkl8c8h91wa5fnb6fk-pcre-8.37/lib, /nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/lib
snapshot-pkg-db: /home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb
local-pkg-db: /home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb
global-pkg-db: /nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
ghc-package-path: /home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb:/home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb:/nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
snapshot-install-root: /home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3
local-install-root: /home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3
snapshot-doc-root: /home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3/doc
local-doc-root: /home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3/doc
dist-dir: .stack-work/dist/x86_64-linux-nix/Cabal-1.22.5.0
local-hpc-root: /home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3/hpc
```

```
> cat stack.yaml
resolver: lts-4.2
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []

nix:
  enable: true
  packages: [glpk, pcre, zlib,
             haskellPackages.cabal-install,
             haskellPackages.hdevtools,
             sublime3, which]
```

**Comment by ch1bo** [comment]
Alright. So hdevtools uses `stack path --ghc-package-path` to determine package-dbs to pass to GHC. Can you find your missing dependencies in there? Or where are these libraries located on your system?

**Comment by chris-martin** [comment]
```
> stack path --ghc-package-path | tr ':' '\n'
/home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb
/home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb
/nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
```

I'm not sure what exactly I should expect to find on this path, so I'll just show you what's there:

```
> ls -l /home/chris/foo/.stack-work/install/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb
total 12
-rw-r--r-- 1 chris users 2588 Feb 15 14:18 Foo-0.1.0.0-7305d22b7cc6a3e9dd92a26de499dff8.conf
-rw-r--r-- 1 chris users 5309 Feb 15 14:18 package.cache
```

```
> ls -l /home/chris/.stack/snapshots/x86_64-linux-nix/lts-4.2/7.10.3/pkgdb
total 1200
-rw-r--r-- 1 chris users   2470 Feb 14 06:16 adjunctions-4.2.2-8e267566278614b439b32f3e0acd9c80.conf
-rw-r--r-- 1 chris users   3906 Feb 14 14:29 aeson-0.10.0.0-2051a74470d6b803196350a81bb95e83.conf
-rw-r--r-- 1 chris users   2030 Feb 14 04:52 ansi-terminal-0.6.2.3-7b40b18f4e53e6f53c2ffd807e929ca9.conf
-rw-r--r-- 1 chris users   1941 Feb 14 04:52 ansi-wl-pprint-0.6.7.3-c624a14e647c937768855ca360a122b5.conf
-rw-r--r-- 1 chris users   2426 Feb 14 14:28 asn1-encoding-0.9.3-74ac4b6f12db7eade4efc60841ab052f.conf
-rw-r--r-- 1 chris users   2111 Feb 14 14:28 asn1-parse-0.9.4-02bd4b213c8353def55148dcd16f2761.conf
-rw-r--r-- 1 chris users   2106 Feb 14 14:28 asn1-types-0.3.2-6f636aa7cbd2e81906e4f75392782c40.conf
-rw-r--r-- 1 chris users   3347 Feb 14 05:20 async-2.0.2-cc5f8dbdd77100b76b8bff0dcef003ab.conf
-rw-r--r-- 1 chris users   3034 Feb 14 14:27 attoparsec-0.13.0.1-183e3fad5061ebaf7371567e93d32ae6.conf
-rw-r--r-- 1 chris users   2627 Feb 14 14:42 authenticate-oauth-1.5.1.1-0875921752b8fe900700dc3b37dbd3b9.conf
-rw-r--r-- 1 chris users   1643 Feb 14 06:16 base16-bytestring-0.1.1.6-e16ffa4271dc3c154e8184c40e44d81e.conf
-rw-r--r-- 1 chris users   1694 Feb 14 06:16 base64-bytestring-1.0.0.1-7a1d6278262346143ad180321424ea8b.conf
-rw-r--r-- 1 chris users   2559 Feb 14 05:19 base-orphans-0.4.5-fd5d4ef84797b48b23d9bf0d3ccf8c05.conf
-rw-r--r-- 1 chris users   2178 Feb 14 05:19 bifunctors-5.1-13b49d7f1dd7301138fa5417c91d6b3f.conf
-rw-r--r-- 1 chris users   2690 Feb 14 06:16 blaze-builder-0.4.0.1-073b5264a38e394a8dbb57adf8acf9c2.conf
-rw-r--r-- 1 chris users   1689 Feb 14 06:16 byteable-0.1.1-8a1589926445fd8ccaca02ef701a2633.conf
-rw-r--r-- 1 chris users   5178 Feb 14 05:24 Cabal-1.22.6.0-032eed835e7e17df077913566bc9600c.conf
-rw-r--r-- 1 chris users   3478 Feb 14 05:24 cabal-helper-0.6.3.0-97f69be50dffc9b7c6714151a566335b.conf
-rw-r--r-- 1 chris users   1938 Feb 14 06:16 case-insensitive-1.2.0.5-6669cd7a393ccedc4f66c0a01b6f0e2f.conf
-rw-r--r-- 1 chris users   2132 Feb 14 05:19 cereal-0.4.1.1-e5a2d88c50e3964865156f13d834ca15.conf
-rw-r--r-- 1 chris users   3869 Feb 14 05:19 cmdargs-0.10.13-456f4ab6dab191e3b8d0a14ac5e0eecf.conf
-rw-r--r-- 1 chris users   2500 Feb 14 05:22 comonad-4.2.7.2-24eef11297bdab67cc9c2306bd539eb2.conf
-rw-r--r-- 1 chris users   2730 Feb 14 14:31 connection-0.2.5-c2b85f51162b475900277fbc1ae36412.conf
-rw-r--r-- 1 chris users   2108 Feb 14 05:21 contravariant-1.3.3-12eeb80222885759c62aaa01fe954a59.conf
-rw-r--r-- 1 chris users   2140 Feb 14 14:26 cookie-0.4.1.6-d9140c4240f67ef825a94ac7a838646d.conf
-rw-r--r-- 1 chris users   2833 Feb 14 05:21 cpphs-1.19.3-360ec8c28045fc6f38fd65dad46ad245.conf
-rw-r--r-- 1 chris users   2804 Feb 14 14:27 crypto-api-0.13.2-992bdf931a769923de7b730e79dfa575.conf
-rw-r--r-- 1 chris users   3459 Feb 14 14:26 cryptohash-0.11.6-34d734c011ff465101201623d7e8253d.conf
-rw-r--r-- 1 chris users   5565 Feb 14 14:29 cryptonite-0.10-05f2c4e5029bfbd18f76b3c34afb1428.conf
-rw-r--r-- 1 chris users   2208 Feb 14 14:28 crypto-pubkey-types-0.4.3-b292c46b84c3855db33da02af51f1761.conf
-rw-r--r-- 1 chris users   2038 Feb 14 14:26 data-default-0.5.3-a34fab0e414a3e31b9dccb1774520fca.conf
-rw-r--r-- 1 chris users   1739 Feb 14 14:26 data-default-class-0.0.1-fcbab95490d730dd2489b628499587cd.conf
-rw-r--r-- 1 chris users   1888 Feb 14 14:26 data-default-instances-base-0.0.1-efbf37e938ab7ef8bb8b5066f40b3866.conf
-rw-r--r-- 1 chris users   2010 Feb 14 14:26 data-default-instances-containers-0.0.1-15c055a1105557a0002bc839699f89f5.conf
-rw-r--r-- 1 chris users   1950 Feb 14 14:26 data-default-instances-dlist-0.0.1-5132c0845fae0bd3d662f332984684d4.conf
-rw-r--r-- 1 chris users   2009 Feb 14 14:26 data-default-instances-old-locale-0.0.1-11796fe51f868bb456c3e6d409bfcc3f.conf
-rw-r--r-- 1 chris users   1498 Feb 14 06:16 Decimal-0.4.2-cd71c3e379974e65bc2aee0a28059f4b.conf
-rw-r--r-- 1 chris users   1602 Feb 14 04:53 digits-0.2-b29a376d27b337d7bcf7dc9190ceb08a.conf
-rw-r--r-- 1 chris users   1991 Feb 14 05:21 distributive-0.4.4-b95ed4231343f39d658fda269121c754.conf
-rw-r--r-- 1 chris users   2036 Feb 14 05:21 djinn-ghc-0.0.2.3-ef614c07bd39d143c7150d184bedb5d2.conf
-rw-r--r-- 1 chris users   1981 Feb 14 05:19 djinn-lib-0.0.1.2-c5d596c806bb7f929e393127ca149c86.conf
-rw-r--r-- 1 chris users   2018 Feb 14 14:26 dlist-0.7.1.2-ff29ea897ce0546ab24638745f33b7b9.conf
-rw-r--r-- 1 chris users   2362 Feb 14 05:23 either-4.4.1-62dcb06948fb5735028e9f3d38bdb8d9.conf
-rw-r--r-- 1 chris users   2277 Feb 14 14:26 entropy-0.3.7-c7ac08f8c292d13469f6d2c87f56ca00.conf
-rw-r--r-- 1 chris users   2082 Feb 14 05:21 exceptions-0.8.2.1-08ed62d2282590eb80eba3e5c42a5f4e.conf
-rw-r--r-- 1 chris users   1711 Feb 14 04:52 extensible-exceptions-0.1.1.4-8159918b63d70675389129eaecbf720a.conf
-rw-r--r-- 1 chris users   2696 Feb 14 05:19 extra-1.4.3-6cc6e988572699d09a8a4936cccaffc9.conf
-rw-r--r-- 1 chris users   4038 Feb 14 05:19 fclabels-2.0.2.3-8675886bb06bef7ad75ea6d9cd3e84c6.conf
-rw-r--r-- 1 chris users   2020 Feb 14 04:52 file-embed-0.0.9-ff9c3618b2938e0d8a6f712b31f2762b.conf
-rw-r--r-- 1 chris users   3786 Feb 14 05:23 free-4.12.4-507e2e692e91775e0f216009b53602d3.conf
-rw-r--r-- 1 chris users   5404 Feb 14 05:31 ghc-mod-5.4.0.0-d129efa6064a4566784fd2c699a3378a.conf
-rw-r--r-- 1 chris users   1632 Feb 14 05:19 ghc-paths-0.1.0.9-1b90c4e6eceac212b6791bafe135b47b.conf
-rw-r--r-- 1 chris users   1825 Feb 14 05:21 ghc-syb-utils-0.2.3-8d21e8e08caf37ffee77fbdea9d23125.conf
-rw-r--r-- 1 chris users   2190 Feb 14 04:59 hashable-1.2.4.0-53b854df9b1b40e67238bc0b030f3c19.conf
-rw-r--r-- 1 chris users   3546 Feb 14 05:27 haskell-src-exts-1.17.1-5b24e5069ca0ab1de212ea615fdf0514.conf
-rw-r--r-- 1 chris users   3007 Feb 14 05:28 hlint-1.9.26-81dcd22b59b9c91d6b88b80861316769.conf
-rw-r--r-- 1 chris users   1569 Feb 14 04:52 hostname-1.0-d89dea758ee32ec5c87a4e8453109323.conf
-rw-r--r-- 1 chris users   2521 Feb 14 14:27 hourglass-0.2.9-2cc4a0c4f77a865a45f6870e2ade79c0.conf
-rw-r--r-- 1 chris users   2528 Feb 14 05:20 hscolour-1.23-8148d8e9e23793389e0f8a3cf06dfe9d.conf
-rw-r--r-- 1 chris users   2640 Feb 14 14:30 hspec-2.2.2-a8c83db179fb734ca682435a61518220.conf
-rw-r--r-- 1 chris users   3066 Feb 14 14:30 hspec-core-2.2.2-24bdb440b560bd2c8a83c946852f3886.conf
-rw-r--r-- 1 chris users   1505 Feb 14 14:27 hspec-discover-2.2.2-8aa4073730c676dbe210ea8bffd8d092.conf
-rw-r--r-- 1 chris users   2099 Feb 14 14:27 hspec-expectations-0.7.2-1eb170687a57c8e4abfbedcdd1830c2c.conf
-rw-r--r-- 1 chris users   3712 Feb 14 14:42 http-client-0.4.26.2-a832cb2eda1ad87024b6e3fe77ba0cdb.conf
-rw-r--r-- 1 chris users   2196 Feb 14 14:42 http-client-tls-0.2.2-264426a55ecab0a880b855528abfc177.conf
-rw-r--r-- 1 chris users   2340 Feb 14 14:27 http-types-0.9-ad629ba2772d26927503c72e0e21d9b9.conf
-rw-r--r-- 1 chris users   1795 Feb 14 04:52 HUnit-1.3.1.0-39c861bc68830b0a4fddc7ed36ad41bb.conf
-rw-r--r-- 1 chris users   2946 Feb 14 14:27 kan-extensions-4.2.3-4fc0771c2a764fc20bc9952a2d559b77.conf
-rw-r--r-- 1 chris users   8652 Feb 14 14:31 lens-4.13-43e898c7396c21160ba3e485bf871d3c.conf
-rw-r--r-- 1 chris users   2338 Feb 14 14:32 lens-aeson-1.0.0.5-ba4d65283c4f749702d21386f4b16879.conf
-rw-r--r-- 1 chris users   3146 Feb 14 14:27 memory-0.10-c3766cb09642b9531dc61e269a593235.conf
-rw-r--r-- 1 chris users   2001 Feb 14 14:28 mime-types-0.1.0.6-140db0eec9a9ff3e0cdd148cbc57c2be.conf
-rw-r--r-- 1 chris users   1701 Feb 14 05:19 mmorph-1.0.5-27d778670624c40cd53adb072747e507.conf
-rw-r--r-- 1 chris users   2842 Feb 14 05:21 monad-control-1.0.0.4-54877a66474b3cf85d4214e0258a1578.conf
-rw-r--r-- 1 chris users   2263 Feb 14 05:23 monad-journal-0.7.1-eb6da16a0aed5a242ea13735ba58b99f.conf
-rw-r--r-- 1 chris users   1872 Feb 14 05:21 MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848.conf
-rw-r--r-- 1 chris users   2426 Feb 14 04:52 mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219.conf
-rw-r--r-- 1 chris users   1689 Feb 14 04:52 multiset-0.3.2-e582cea8b8165e76d641c7fdf7a9b5fd.conf
-rw-r--r-- 1 chris users   3024 Feb 14 14:29 network-2.6.2.1-25f4f3b167c1b84622324351cf72302e.conf
-rw-r--r-- 1 chris users   2526 Feb 14 14:29 network-uri-2.6.0.3-498487433ab76db2bf1078a5ce1815a8.conf
-rw-r--r-- 1 chris users   1588 Feb 14 04:52 old-locale-1.0.0.7-0db938eb141b01f4936a21aef6b843bf.conf
-rw-r--r-- 1 chris users   1857 Feb 14 05:20 old-time-1.1.0.3-4494378134a1c0eadea2f9ea5411834e.conf
-rw-r--r-- 1 chris users 639476 Feb 14 14:43 package.cache
-rw-r--r-- 1 chris users   1933 Feb 14 14:29 parallel-3.2.1.0-13fa56575e4752a542f0b618706881f7.conf
-rw-r--r-- 1 chris users   2937 Feb 14 14:29 parsec-3.1.9-c97a6d9077152efda935fd305a6ba92b.conf
-rw-r--r-- 1 chris users   2071 Feb 14 14:29 pem-0.2.2-5f6df2ca3b7f68abc9010881cb82b5dd.conf
-rw-r--r-- 1 chris users   2555 Feb 14 05:20 pipes-4.1.7-47c60d131e53ab6d6b7e6fd6c5929c84.conf
-rw-r--r-- 1 chris users   2709 Feb 14 05:20 polyparse-1.11-9f36f5473e0ff7e0bc4a41846284cdc6.conf
-rw-r--r-- 1 chris users   1968 Feb 14 05:20 prelude-extras-0.4.0.3-35d27727606bcd0bcd2c3491f65bf5b7.conf
-rw-r--r-- 1 chris users   1831 Feb 14 04:52 primes-0.2.1.0-6cf6fc13c1674887d9ef9b97a5d08d52.conf
-rw-r--r-- 1 chris users   2265 Feb 14 04:52 primitive-0.6.1.0-b2a7b9f8d5591c0d4ce7ef238a3217d2.conf
-rw-r--r-- 1 chris users   2314 Feb 14 05:22 profunctors-5.1.2-5cd2a3d122f0b346b105c5fda8f379a8.conf
-rw-r--r-- 1 chris users   3907 Feb 14 14:29 psqueues-0.2.0.3-84f6eba20019e2166992e8a1868d0a2e.conf
-rw-r--r-- 1 chris users   2159 Feb 14 14:29 pureMD5-2.1.2.1-ce2d9722727de9d036ac41a9702f767a.conf
-rw-r--r-- 1 chris users   3015 Feb 14 04:53 QuickCheck-2.8.1-8a87b464a167a1dd789e3a0c72a16364.conf
-rw-r--r-- 1 chris users   2062 Feb 14 14:29 quickcheck-io-0.1.2-92368564b1535a1a0ca98bea630eed0b.conf
-rw-r--r-- 1 chris users   1621 Feb 14 04:52 random-1.1-c46cc413d88c0a330b5495d03f0ed464.conf
-rw-r--r-- 1 chris users   1706 Feb 14 05:20 refact-0.3.0.2-1cd472adb3e18a619aee233f5bb24ee0.conf
-rw-r--r-- 1 chris users   2882 Feb 14 14:29 reflection-2.1.1.1-85822cc089c178bf4a18f476220ac065.conf
-rw-r--r-- 1 chris users   2104 Feb 14 04:52 regex-base-0.93.2-9b0397e37aed6ad688fc1903d4747075.conf
-rw-r--r-- 1 chris users   2157 Feb 14 04:52 regex-posix-0.95.2-6e2e8d9c875d7561ec5287f5dc3121d1.conf
-rw-r--r-- 1 chris users   2459 Feb 14 14:29 RSA-2.2.0-ad5c634408008cf1919f41c5650e65ca.conf
-rw-r--r-- 1 chris users   3788 Feb 14 04:59 scientific-0.3.4.4-12411058317f77b18d2dfe2db60a1d91.conf
-rw-r--r-- 1 chris users   4954 Feb 14 05:22 semigroupoids-5.0.1-0cb924a0ec57f8fe62c996d9ba74cd9e.conf
-rw-r--r-- 1 chris users   2486 Feb 14 04:59 semigroups-0.18.0.1-93b0d4bc48bcbf1531cd14569540aaa9.conf
-rw-r--r-- 1 chris users   2070 Feb 14 14:29 setenv-0.1.1.3-4d70f2e61b1bd0645017164a0ca26ee9.conf
-rw-r--r-- 1 chris users   2391 Feb 14 14:29 SHA-1.6.4.2-77809b6ff18053a556c8f0a1e4b17672.conf
-rw-r--r-- 1 chris users   2146 Feb 14 14:30 socks-0.5.4-455f8c7a01a0b41093080960af7489d0.conf
-rw-r--r-- 1 chris users   2534 Feb 14 05:20 split-0.2.3-8ed100aa18239d92816021c44aa12b38.conf
-rw-r--r-- 1 chris users   1872 Feb 14 05:20 StateVar-1.1.0.3-8283c9355d2fc1ad397281acceca5467.conf
-rw-r--r-- 1 chris users   1827 Feb 14 05:20 stm-2.4.4.1-7050c728ed5b2315e2c6b56d8bf9837f.conf
-rw-r--r-- 1 chris users   3177 Feb 14 14:42 streaming-commons-0.1.15-d0d7670000b39b991fdcf44505b61f4c.conf
-rw-r--r-- 1 chris users   2212 Feb 14 05:20 syb-0.6-d154b8ffa473f7cfcfc32ca4d99f62f7.conf
-rw-r--r-- 1 chris users   1836 Feb 14 04:52 tagged-0.8.2-16a51d8cfafeba080a9011b87265d84b.conf
-rw-r--r-- 1 chris users   2563 Feb 14 05:21 temporary-1.2.0.3-811c17ef1fdb1b21cc6d391ba74b165d.conf
-rw-r--r-- 1 chris users   3475 Feb 14 04:59 test-framework-0.8.1.1-ade54124d65b376a4d663cbcc03924d8.conf
-rw-r--r-- 1 chris users   1983 Feb 14 04:59 test-framework-hunit-0.3.0.2-c27e68f1ec106072c4011a4e0d20efb9.conf
-rw-r--r-- 1 chris users   4402 Feb 14 04:58 text-1.2.2.0-2c09cfae3213a07ad08b7cc1c9a4bb52.conf
-rw-r--r-- 1 chris users   3288 Feb 14 04:52 tf-random-0.5-be1be3a7eeba5ee8baa6cee25a76f884.conf
-rw-r--r-- 1 chris users   2021 Feb 14 14:29 time-locale-compat-0.1.1.1-4bbdeebce90c671369911a4d16cfee44.conf
-rw-r--r-- 1 chris users   4569 Feb 14 14:30 tls-1.3.4-40bfaa5ed7f6abd24f3ff22dbfb27c22.conf
-rw-r--r-- 1 chris users   2175 Feb 14 05:21 transformers-base-0.4.4-19dc155e74aa624600f63b02f5f0b424.conf
-rw-r--r-- 1 chris users   2363 Feb 14 05:21 transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092.conf
-rw-r--r-- 1 chris users   3932 Feb 14 05:21 uniplate-1.6.12-cf70c5831d9c10583f7d960d54150ac6.conf
-rw-r--r-- 1 chris users   2328 Feb 14 04:59 unordered-containers-0.2.5.1-1d8b785d5ff15d73cea879f09e714589.conf
-rw-r--r-- 1 chris users   1940 Feb 14 05:21 utf8-string-1.0.1.1-09f6924ad5da4f093413455bda66bd2c.conf
-rw-r--r-- 1 chris users   3340 Feb 14 04:59 vector-0.11.0.0-299aefb173ce5a731565d31f609a0cfd.conf
-rw-r--r-- 1 chris users   1924 Feb 14 05:21 void-0.7.1-17d082772e8624957130c19d9a33d997.conf
-rw-r--r-- 1 chris users   4177 Feb 14 14:43 wreq-0.4.1.0-3a480fd8ab6aee65bffed30a24f3aa52.conf
-rw-r--r-- 1 chris users   2647 Feb 14 14:30 x509-1.6.3-71b74eb2d9b910708024543fa011ebcb.conf
-rw-r--r-- 1 chris users   2406 Feb 14 14:30 x509-store-1.6.1-565e6b066c75c1da5b3f7c0d67883bd5.conf
-rw-r--r-- 1 chris users   2402 Feb 14 14:30 x509-system-1.6.3-a560d4a3b36f93fe3b17367b45549556.conf
-rw-r--r-- 1 chris users   2792 Feb 14 14:30 x509-validation-1.6.3-16662c0723ae0ff9247c134182cf66f9.conf
-rw-r--r-- 1 chris users   1778 Feb 14 04:59 xml-1.3.14-a73a3480c7e207c7cc716aeb6111947b.conf
-rw-r--r-- 1 chris users   2428 Feb 14 14:42 zlib-0.6.1.1-15b43d31c29ab042806f5856753cf1a1.conf
```

```
> ls -l /nix/store/xyzzg5cbk1kh1n4s2q9n76lrqnzxxld8-ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
total 252
-r--r--r-- 1 root root   1639 Dec 31  1969 array-0.5.1.0-960bf9ae8875cc30355e086f8853a049.conf
-r--r--r-- 1 root root   4781 Dec 31  1969 base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d.conf
-r--r--r-- 1 root root   1980 Dec 31  1969 binary-0.7.5.0-bf6a937522bb8cec5d00218470f28789.conf
-r--r--r-- 1 root root   1859 Dec 31  1969 bin-package-db-0.0.0.0-c2998655922e5892be4d23c583233dd1.conf
-r--r--r-- 1 root root   2869 Dec 31  1969 builtin_rts.conf
-r--r--r-- 1 root root   4340 Dec 31  1969 bytestring-0.10.6.0-9a873bcf33d6ce2fd2698ce69e2c1c66.conf
-r--r--r-- 1 root root   4708 Dec 31  1969 Cabal-1.22.5.0-7f02ff9ebe9d6ee20c4f88e79d93e5f2.conf
-r--r--r-- 1 root root   1736 Dec 31  1969 containers-0.5.6.2-59326c33e30ec8f6afd574cbac625bbb.conf
-r--r--r-- 1 root root   1739 Dec 31  1969 deepseq-1.4.1.1-614b63b36dd6e29d2b35afff57c25311.conf
-r--r--r-- 1 root root   1456 Dec 31  1969 directory-1.2.2.0-660a7a83a753ed85c8a374c15dae2b97.conf
-r--r--r-- 1 root root   1950 Dec 31  1969 filepath-1.4.0.0-f97d1e4aebfd7a03be6980454fe31d6e.conf
-r--r--r-- 1 root root   7350 Dec 31  1969 ghc-7.10.3-0e1450febd11b881251bd2631dcd38f5.conf
-r--r--r-- 1 root root   1071 Dec 31  1969 ghc-prim-0.4.0.0-6cdc86811872333585fa98756aa7c51e.conf
-r--r--r-- 1 root root   3098 Dec 31  1969 haskeline-0.7.2.1-ee66b80ab55ef13718feae46e4940f5d.conf
-r--r--r-- 1 root root   2043 Dec 31  1969 hoopl-3.10.0.2-e1d2f66d9c173061362d378e84471a99.conf
-r--r--r-- 1 root root   1417 Dec 31  1969 hpc-0.6.0.2-a33eebda3a4ae222891fd5d14c4f2b1f.conf
-r--r--r-- 1 root root   1460 Dec 31  1969 integer-gmp-1.0.0.0-3c8c40657a9870f5c33be17496806d8d.conf
-r--r--r-- 1 root root 138847 Dec 31  1969 package.cache
-r--r--r-- 1 root root   1570 Dec 31  1969 pretty-1.1.2.0-5cc412214ea63f61ee84c4fbabdbe0ec.conf
-r--r--r-- 1 root root   1456 Dec 31  1969 process-1.2.3.0-a22328103774f0499a990653944cbf99.conf
-r--r--r-- 1 root root   1539 Dec 31  1969 template-haskell-2.10.0.0-3c4cb52230f347282af9b2817f013181.conf
-r--r--r-- 1 root root   1837 Dec 31  1969 terminfo-0.4.0.1-ff5b3d5838955b7711e16ccc720f06f4.conf
-r--r--r-- 1 root root   1937 Dec 31  1969 time-1.5.0.1-1b9a502bb07a3e6f4d6935fbf9db7181.conf
-r--r--r-- 1 root root   2874 Dec 31  1969 transformers-0.4.2.0-81450cd8f86b36eaa8fa0cbaf6efc3a3.conf
-r--r--r-- 1 root root   2700 Dec 31  1969 unix-2.7.1.0-bb54ee8f9f6b2600aae7a748eb88a610.conf
-r--r--r-- 1 root root   1787 Dec 31  1969 xhtml-3000.2.1-e005917157f780654d68110616d034e8.conf
```

**Comment by chris-martin** [comment]
I notice someone experimented with a fix a while back of passing the package path explicitly to GHC: https://github.com/parsonsmatt/hdevtools/commit/0a25c74082d4c8841ac3d89d7d8f5a75f0673796 - does this look relevant?

**Comment by ch1bo** [comment]
Hm..the dependencies reported missing should be in the snapshot package db.

Before we debug what is actually passed to GHC. How did you install hdevtools? Does running `stack exec --no-ghc-package-path hdevtools -- check ...`, i.e. as direct argument make a difference? In case you installed it with nix (as I said i dont have a clue about that) can you try to install it wirh stack?

**Comment by ch1bo** [comment]
Also, what dies direct invocation, as ranjit said, give you?

**Comment by ilikebits** [comment]
I'm experiencing the same issue -- direct invocation gives the same missing dependencies error. I installed with `stack`, and my `hdevtools --version` is `hdevtools: version 0.1.2.2 (ghc-7.10.3-x86_64-linux, cabal-1.22.7.0)`.

**Comment by ranjitjhala** [comment]
Is there a public repo / codebase that you can point us to that we can use
to try to reproduce the problem?
​

**Comment by ilikebits** [comment]
Just kidding, I'm an idiot. It was failing on my test files because I forgot to `stack test` after I pulled the code, and my test-only dependencies weren't built!

**Comment by ranjitjhala** [comment]
ah, no worries! :)

**Comment by ch1bo** [comment]
Any news on this? Is this resolved?

**Comment by chris-martin** [comment]
Not resolved, though I haven't been back to it in a while.

**Comment by ch1bo** [comment]
I just improved stack support on branch `stack-ghc-libdir` branch. This version does not require execution via `stack exec` anymore, so a direct invocation should find your compiler and packages correctly.

**Comment by ranjitjhala** [comment]
Awesome -- should we merge into master?

**Comment by ch1bo** [comment]
Wanted to wait for some feedback on the issues first but looks good so far.

**Comment by ranjitjhala** [comment]
OK I'll give it a whirl!

**Comment by ch1bo** [comment]
Closing this in course of release 0.1.4.0 which should solve this.

**Comment by ranjitjhala** [comment]
Hmm. I'm still getting this:

```
jhala@localhost ~/t/1/fer-de-lance (megaparsec) [1]> stack exec -- hdevtools check lib/Language/FDL/MegaParse.hs 
Cabal error: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times).
```

and 

```
jhala@localhost ~/t/1/fer-de-lance (megaparsec) [1]> stack exec -- hdevtools --help
hdevtools: version 0.1.4.0 (ghc-7.10.3-x86_64-darwin, cabal-1.22.8.0)
```

is this due to the older `cabal`? [I built with lts-5.9 not lts-6.10]

**Comment by ch1bo** [comment]
hdevtools does not need to be run bia stack exec anymore to correctlt locate compilers and packages. Does calling hdevtools directly work?

**Comment by ranjitjhala** [comment]
With the "lts-5.9" version, without `stack exec` it was complaining that it couldn't find GHC...

Am currently rebuilding with `lts-6.10`.

**Comment by ranjitjhala** [comment]
Specifically, I get:

```
jhala@localhost ~/t/1/fer-de-lance (megaparsec) [1]> hdevtools check lib/Language/FDL/MegaParse.hs 
Cabal error: The program 'ghc' version >=6.4 is required but it could not be found.
```

This is because the `ghc` was itself located wherever `stack` put it (not in the global path). 

So I did:

```
$  stack exec -- which ghc
/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc
```

and then added the above path to my `$PATH` -- after which its working!

**Comment by ch1bo** [comment]
Can you call with `check xxx --debug`, I added some prints to see whether it finds the stack file.

**Comment by ch1bo** [comment]
I cannot reproduce your situation, even if I remove all GHCs from my path, hdevtools runs without errors. Maybe you still have an (old) hdevtools socket file lying around? Try `hdevtools --stop-server` from your call site.

**Comment by ranjitjhala** [comment]
​I was wiping all old hdevtools -- but let me try again.
​

**Comment by ranjitjhala** [comment]
Hmm, still no luck for me.


```

jhala@localhost ~/t/1/fer-de-lance (megaparsec) [1]> which ghc

jhala@localhost ~/t/1/fer-de-lance (megaparsec) [1]> hdevtools --stop-server

Shutting down server.

jhala@localhost ~/t/1/fer-de-lance (megaparsec)> hdevtools check
lib/Language/FDL/MegaParse.hs --debug

Cabal file: Just "/Users/jhala/teaching/131/fer-de-lance/./fdl.cabal"

Stack file: Just "/Users/jhala/teaching/131/fer-de-lance/stack.yaml"

Socket file: "/Users/jhala/teaching/131/fer-de-lance/./.hdevtools.sock"

Cabal error: The program 'ghc' version >=6.4 is required but it could not
be found.

```


My only `ghc` is the one that stack has installed in

```
/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc
```

Am guessing you've done a `which ghc` to confirm its not on your path?

**Comment by ch1bo** [comment]
Yeah.. hm can you add this 
```
diff --git a/src/Cabal.hs b/src/Cabal.hs
index 253adbd..ebc0834 100644
--- a/src/Cabal.hs
+++ b/src/Cabal.hs
@@ -155,6 +155,7 @@ getPackageGhcOpts path mbStack opts = do
             CommandErrors (e:_) -> error e
             _ -> return ()
 
+        putStrLn $ "before configure: " ++ show cfgFlags
         localBuildInfo <- configure (genPkgDescr, emptyHookedBuildInfo) cfgFlags
         let pkgDescr = localPkgDescr localBuildInfo
         let baseDir = fst . splitFileName $ path
```
and then start `hdevtools --start-server -n` and in another terminal do the check call which fails?

**Comment by ranjitjhala** [comment]
Here's the result:

```
jhala@localhost ~/t/1/fer-de-lance (megaparsec) [1]> hdevtools --start-server -n
before configure: ConfigFlags {configPrograms = [], configProgramPaths = [], configProgramArgs = [], configProgramPathExtra = [], configHcFlavor = Flag GHC, configHcPath = Flag "/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc", configHcPkg = Flag "/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc-pkg", configVanillaLib = Flag True, configProfLib = NoFlag, configSharedLib = NoFlag, configDynExe = Flag False, configProfExe = NoFlag, configConfigureArgs = [], configOptimization = Flag NormalOptimisation, configProgPrefix = Flag "", configProgSuffix = Flag "", configInstallDirs = InstallDirs {prefix = NoFlag, bindir = NoFlag, libdir = NoFlag, libsubdir = NoFlag, dynlibdir = NoFlag, libexecdir = NoFlag, includedir = NoFlag, datadir = NoFlag, datasubdir = NoFlag, docdir = NoFlag, mandir = NoFlag, htmldir = NoFlag, haddockdir = NoFlag, sysconfdir = NoFlag}, configScratchDir = NoFlag, configExtraLibDirs = [], configExtraIncludeDirs = [], configDistPref = Flag ".stack-work/dist/x86_64-osx/Cabal-1.22.5.0", configVerbosity = Flag Normal, configUserInstall = Flag True, configPackageDBs = [Nothing,Just GlobalPackageDB,Just (SpecificPackageDB "/Users/jhala/teaching/131/fer-de-lance/.stack-work/install/x86_64-osx/lts-6.10/7.10.3/pkgdb"),Just (SpecificPackageDB "/Users/jhala/.stack/snapshots/x86_64-osx/lts-6.10/7.10.3/pkgdb"),Just (SpecificPackageDB "/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/lib/ghc-7.10.3/package.conf.d")], configGHCiLib = NoFlag, configSplitObjs = Flag False, configStripExes = Flag True, configStripLibs = Flag True, configConstraints = [], configDependencies = [], configInstantiateWith = [], configConfigurationsFlags = [], configTests = Flag True, configBenchmarks = Flag True, configCoverage = Flag False, configLibCoverage = NoFlag, configExactConfiguration = Flag False, configFlagError = NoFlag, configRelocatable = Flag False, configDebugInfo = Flag NoDebugInfo}
Configuring fdl-0.1.0.0...
before configure: ConfigFlags {configPrograms = [], configProgramPaths = [], configProgramArgs = [], configProgramPathExtra = [], configHcFlavor = Flag GHC, configHcPath = Flag "/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc", configHcPkg = Flag "/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc-pkg", configVanillaLib = Flag True, configProfLib = NoFlag, configSharedLib = NoFlag, configDynExe = Flag False, configProfExe = NoFlag, configConfigureArgs = [], configOptimization = Flag NormalOptimisation, configProgPrefix = Flag "", configProgSuffix = Flag "", configInstallDirs = InstallDirs {prefix = NoFlag, bindir = NoFlag, libdir = NoFlag, libsubdir = NoFlag, dynlibdir = NoFlag, libexecdir = NoFlag, includedir = NoFlag, datadir = NoFlag, datasubdir = NoFlag, docdir = NoFlag, mandir = NoFlag, htmldir = NoFlag, haddockdir = NoFlag, sysconfdir = NoFlag}, configScratchDir = NoFlag, configExtraLibDirs = [], configExtraIncludeDirs = [], configDistPref = Flag ".stack-work/dist/x86_64-osx/Cabal-1.22.5.0", configVerbosity = Flag Normal, configUserInstall = Flag True, configPackageDBs = [Nothing,Just GlobalPackageDB,Just (SpecificPackageDB "/Users/jhala/teaching/131/fer-de-lance/.stack-work/install/x86_64-osx/lts-6.10/7.10.3/pkgdb"),Just (SpecificPackageDB "/Users/jhala/.stack/snapshots/x86_64-osx/lts-6.10/7.10.3/pkgdb"),Just (SpecificPackageDB "/Users/jhala/.stack/programs/x86_64-osx/ghc-7.10.3/lib/ghc-7.10.3/package.conf.d")], configGHCiLib = NoFlag, configSplitObjs = Flag False, configStripExes = Flag True, configStripLibs = Flag True, configConstraints = [], configDependencies = [], configInstantiateWith = [], configConfigurationsFlags = [], configTests = Flag True, configBenchmarks = Flag True, configCoverage = Flag False, configLibCoverage = NoFlag, configExactConfiguration = Flag False, configFlagError = NoFlag, configRelocatable = Flag False, configDebugInfo = Flag NoDebugInfo}
Configuring fdl-0.1.0.0...
```

**Comment by ranjitjhala** [comment]
Looks like it knows where `ghc` is, but perhaps its not being passed to cabal `--path-to-ghc` ?
